<?php
return [
    "title_banner" => "Job Posting",
    "description_banner_1" => "And Effective Candidate Search",
    "description_banner_2" => "We provide online recruitment information with swift, reliable, and accurate approvals.",
    "find_now" => "Find Now",

    "big_upgrade" => "| Big Upgrade",
    "description_big_upgrade_1" => "We are harnessing the power of information technology to build a robust bridge between <br>the student community and businesses. Our system not only facilitates students in easily searching and connecting with job opportunities that align with their skills and interests but also provides comprehensive solutions for the challenges that businesses encounter in the recruitment process.",
    "description_big_upgrade_2" => "Simultaneously, businesses can benefit from accessing a diverse and high-quality pool of candidates, thanks to the intelligent interaction capabilities on our platform. In this way, we are supporting not only the job search process but also the development and optimization of human resources for enterprises, creating a win-win environment for both students and businesses.",

    "new_feature" => "| New Feature. A Fresh Experience!",
    "description_new_feature_1" => "Recruitment Portal, a product of cutting-edge information technology, is meticulously designed to revolutionize the hiring process. By leveraging advanced data analytics, the portal thoroughly examines the requirements, habits, and behaviors of both recruiters and candidates. This comprehensive analysis serves as the foundation for generating insightful predictions and strategic recommendations aimed at optimizing recruitment practices.",
    "description_new_feature_2" => "Moreover, the Recruitment Portal acts as an intelligent advisor, offering real-time feedback and performance metrics. It empowers recruiters to make data-driven decisions, ultimately streamlining the hiring process and ensuring a more precise alignment between talent acquisition strategies and organizational objectives. With its forward-thinking features, this portal represents a leap forward in the realm of recruitment technology, promising a future where every hiring decision is informed, efficient, and tailored to the unique dynamics of each business.",

    "about_us" => "| About us",
    "description_about_us_1" => "The College of Information and Communication Technology is honored to be one of the seven faculties/schools pioneering in Vietnam, responsible for training engineers since 1990. With 33 years of construction and development, The College of Information and Communication Technology brand has become a prestigious institution providing high-quality human resources for the domestic and international labor markets. The school's mission is to train engineers, masters, and doctors specializing in the field of IT and related fields, actively contributing to the development of Vietnam's information technology industry; simultaneously conducting scientific research and transferring advanced technology to promote the industrialization and modernization of the country.",
    "description_about_us_2" => "The College of Information and Communication Technology consists of 6 departments and 4 affiliated units. Each department is responsible for training in specific majors and specializations. In terms of training scale, the school is currently responsible for training 10 majors and specializations at the bachelor's level, 3 majors at the master's level, and 1 major at the doctoral level, with a total enrollment of over 5,000 students. Regarding the faculty, the school currently has 123 staff members (104 teaching staff and 19 support/service staff), including 5 associate professors, 46 doctors, and 58 masters. The majority of the faculty members have been trained at advanced universities abroad.",
    "description_about_us_3" => "In the context of the digital transformation and the fourth industrial revolution, the school has consistently focused on enhancing development in all aspects, both in terms of quality and scale. The College of Information and Communication Technology possesses modern facilities and a strong and comprehensive faculty. Particularly in recent years, The College of Information and Communication Technology has been honored with prestigious awards such as the Emulation Flag and Commendation Certificate from the Ministry of Education and Training, the Commendation Certificate from the Prime Minister, and the Labor Order from the President.",

    "mission" => "| Mission and vision",
    "description_mission_1" => "The College of Information and Communication Technology is to provide education, conduct scientific research, and transfer technology in the field of IT and Communication, as well as related areas, to serve the industrialization and modernization of the country.",
    "description_mission_2" => "Looking towards 2030, the College of Information and Communication Technology aspires to become a strong and reputable university in the field of IT and Communication in the Asian region, achieving international standards for quality assurance in education.",
    "description_mission_3" => "The core values of the College of Information and Communication Technology are Consensus - Devontion - Quality - Innovation.",
    "description_mission_4" => "The educational philosophy of The College of Information and Communication Technology is Critical Thinking, Creativity, with the learner at the center.",

    "overview" => "| Overview Of Collaboration",
    "description_overview_1" => "The College of Information and Communication Technology consistently emphasizes strengthening collaborative relationships with traditional partners from France and Canada, while actively expanding cooperation with new partners from the UK, the US, Australia, and Asia. In addition, the school proactively seeks, deploys, and successfully executes various international projects, providing many opportunities for faculty and students to study/research abroad.",
    "description_overview_2" => "The College of Information and Communication Technology collaborates with numerous software companies to train students in specialized skills and develop software products. The school also engages in extensive collaboration with many provinces and cities in Vietnam, both in the digital transformation initiatives and in research and development of software products. In addition to hundreds of Memoranda of Understanding (MoUs) signed at the university level in Can Tho, The College of Information and Communication Technology has signed MoUs with over 50 companies, both domestic and international. Annually, the school reviews and evaluates the signed MoUs to develop specific plans, further enhancing collaborative relationships with partners.",
    "description_overview_3" => "This efficient bridge-building between the university and the business sector contributes to elevating the university's brand. Through these activities, the school receives substantial sponsorship from companies, ranging from scholarships for students to research equipment.",

    "partner" => "| Some prominent partners"
];